name: NPC
version: "${pom.version}"
api: ["1.0.9"]
author: PetteriM1
main: idk.plugin.npc.NPC

commands:
  npc:
    description: NPC command
    usage: "/npc"
    permission: npc.edit
permissions:
  npc.edit:
    description: "NPC permission"
    default: op
