name: NPC
version: "${pom.version}"
api: ["1.0.14"]
author: PetteriM1
main: idk.plugin.npc.NPC
load: STARTUP

commands:
  npc:
    description: Spawn and modify NPCs
    usage: "/npc [action]"
    permission: npc.edit
permissions:
  npc.edit:
    description: "Allows the player to spawn and modify NPCs"
    default: op
